services:
  yarrrml-parser:
    environment:
      - PORT=${PARSER_PORT}
    image: ghcr.io/mi-fraunhoferiwm/yarrrml-parser:latest
    expose:
      - ${PARSER_PORT}
    restart: always
    networks:
      - json2rdf_net

  rmlmapper:
    environment:
      - PORT=${MAPPER_PORT}
    image: ghcr.io/mi-fraunhoferiwm/rmlmapper:latest
    expose:
      - ${MAPPER_PORT}
    restart: always
    networks:
      - json2rdf_net

  json2rdf:
    environment:
      - parser_url=http://yarrrml-parser:${PARSER_PORT}
      - mapper_url=http://rmlmapper:${MAPPER_PORT}
    image: ghcr.io/mi-fraunhoferiwm/json2rdf:latest
    ports:
      - ${CONV_PORT}:${API_PORT}
    restart: always
    networks:
      - json2rdf_net

networks:
  json2rdf_net:
    name: json2rdf_net
    driver: bridge
