services:
  yarrrml-parser:
    container_name: yarrrml-parser
    environment:
      - PORT=3001
    build: ./yarrrml-parser
    expose:
      - 3001
    restart: always
    networks:
      - json2rdf_net

  rmlmapper:
    environment:
      - PORT=4000
    container_name: rmlmapper
    build: ./rmlmapper-webapi
    expose:
      - 4000
    restart: always
    networks:
      - json2rdf_net

  json2rdf:
    environment:
      - parser_url=http://yarrrml-parser:3001
      - mapper_url=http://rmlmapper:4000
    container_name: json2rdf
    build: ./api
    ports:
      - ${JSON2RDF_PORT}:5000
    restart: always
    networks:
      - json2rdf_net

networks:
  json2rdf_net:
    name: json2rdf_net
    driver: bridge
